### PR TITLE
fix: JSON escape

### LINKED ISSUE #10: Wrong json format
Example:
```
{"level":"info","ts":"2021-06-16T08:41:00.863+0000","logger":"neptune::proteus::gpu","caller":"/home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/neptune-2.7.0/src/proteus/gpu.rs:183","msg":"device: Device { brand: Nvidia, name: "GeForce RTX 3080", memory: 10504699904, bus_id: Some(65), platform: Platform(PlatformId(0x7f9964029660)), device: Device(DeviceId(0x7f996406cdc0)) }"}
```

Should be

```diff
-"msg":"device: Device { brand: Nvidia, name: "GeForce RTX 3080", memory: 10504699904, bus_id: Some(65), platform: Platform(PlatformId(0x7f9964029660)), device: Device(DeviceId(0x7f996406cdc0)) }"
+"msg":"device: Device { brand: Nvidia, name: \"GeForce RTX 3080\", memory: 10504699904, bus_id: Some(65), platform: Platform(PlatformId(0x7f9964029660)), device: Device(DeviceId(0x7f996406cdc0)) }"
```

### PR DESCRIPTION
**Pull request by Aloxaf**
The content of "msg" should be escaped.

Fix #10

### CODE REVIEW

**Review by vmx — COMMENTED** [review]
Thanks for the PR. I've a few concerns about the library that you use for the JSON escaping. While it is nice to have an highly optimized one, I fear silent breakage a bit.

I'd like to release this fix as a patch version, so that upstream releases can benefit from it. What do you think about using the non-simd fallback via `v_jsonescape::fallback::escape()` for now (just to be safe) and we can then later, in a breaking change (perhaps with an upgrade to the latest flexi_logger release) enable the SIMD version?

**Comment by Aloxaf** [comment]
Thanks for your advice! That's indeed a better solution.

I have updated the code.

**Comment by vmx** [comment]
@cryptonemo @dignifiedquire I'd like your input on this one. I'd like to release it as a patch version as it is really annoying that we don't escape the messages correctly.

Though the escaping dependency is a bit scary, though we use the non-simd code path. So I think we should be fine. If it were me, I'd release it as a patch version => also include it in possible future releases of rust-fil-proofs. What do you think?

**Comment by Aloxaf** [comment]
Maybe we can also use `{:?}` here? It can also escape `"` correctly, which is enough for our simple case.

**Comment by vmx** [comment]
@Aloxaf that's a good idea and simple enough. Would you mind opening a new PR, so we can keep that one for future reference, in case we want to implement it with proper JSON escaping.

**Comment by Aloxaf** [comment]
> @Aloxaf that's a good idea and simple enough. Would you mind opening a new PR, so we can keep that one for future reference, in case we want to implement it with proper JSON escaping.

done, see #12.

**Comment by vmx** [comment]
@cryptonemo @dignifiedquire nevermind, we found a simpler, more robust solution for now.

**Comment by vmx** [comment]
Fixed by https://github.com/filecoin-project/rust-fil-logger/pull/12 and released as 0.1.3.

**Pull request closed without merging**
